CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS measurement;

DROP TABLE IF EXISTS location;
CREATE TABLE location (
    system_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    light_source_count INTEGER NOT NULL DEFAULT 0,
    geometry geometry(Point, 4326) NOT NULL
);

CREATE TABLE measurement (
    system_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_val DOUBLE PRECISION,
    min_val DOUBLE PRECISION,
    avg_val DOUBLE PRECISION,
    location_system_id BIGINT NOT NULL REFERENCES location(system_id)
);

CREATE INDEX idx_location_geometry ON location USING GIST (geometry);